### ISSUE TITLE
Invalid login

### ISSUE THREAD

**Issue by Djon21** [LostSoulfly/MinerProxy2#2]
Hi!
Server error for s1.solopool.org:8011: -1 Invalid login

How to fix it?

**Comment by LostSoulfly** [comment]
Looking at their Help page, it looks like the default protocol will send
Wallet.poolWorkerName which is not compatible with their system. You will
need to set the poolProtocol to 1 to use the alternate login method.

[image: image.png]

[image: image.png]

**Comment by Djon21** [comment]
Thanks, it worked!
